#!/bin/bash

printf "\nRunning TSLint:\n\n"

npm --silent run lint

if [ $? -eq 0 ]; then
    printf "Successfully Lint'd\n"
    exit 0
else
    printf "Lint errors found (see above), please fix and try again.\n\n"
    exit 1
fi